[package]
name = "advents-of-code"
version = "0.1.0"
authors = ["Maxim Baz"]
edition = "2018"

[dependencies]
itertools = "0.9.0"
regex = "1"
strum = "0.20"
strum_macros = "0.20"
lazy_static = "1.4.0"
